export const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED';
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED';
export const USERS_FETCH_SUCCEEDED = 'USERS_FETCH_SUCCEEDED';

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
